set -g default-terminal "screen-256color"
set -g display-time 3000
set -g history-limit 1000000
set -g base-index 1
set -g pane-base-index 1
set -s escape-time 0
set -g mouse on
set -g prefix C-a
set -g set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u
unbind-key C-b
bind-key C-a send-prefix

if-shell "uname | grep -q 'Darwin'" 'set-option -g default-shell "/usr/local/bin/fish"'

bind-key t new-window -c "#{pane_current_path}"
bind-key c kill-window 

bind-key B 'choose-tree -Zw "join-pane -s '"'"'%%'"'"'"'
bind-key b if-shell '[ #{window_panes} -gt 1 ]' \
        'break-pane -d' \
        'choose-tree -Zw "join-pane -h -s '"'"'%%'"'"'"'

bind-key Space display-menu -T "选择布局" \
  "左右对调"  s  "swap-pane -D" \
  "左右均分"  h  "select-layout even-horizontal"  \
  "上下对调"  S  "swap-pane -D" \
  "上下均分"  v  "select-layout even-vertical"    \
  "网格均分"  t  "select-layout tiled"


bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v  -c "#{pane_current_path}" 
bind -n C-p setw synchronize-panes
bind-key -n C-l send-keys C-l \; send-keys -R \; clear-history

bind-key o run-shell -b "tmux popup -xC -yC -w100% -h75% -E $HOME/bin/snippte &> /dev/null"
bind-key v if-shell -F '#{==:#{session_name},p-shell}' { 
        detach-client 
} {
    run-shell -b "tmux popup -E -d '#{pane_current_path}' -w70% -h70% \"tmux attach -t p-shell || tmux new -s p-shell\" || true"
}

setw -g mode-keys vi
setw -gq utf8 on
set -g mouse on

bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "$(if [[ $(uname) == 'Darwin' ]]; then echo 'pbcopy'; else echo 'xclip -in -selection clipboard'; fi)"

bind p run 'FILENAME=/tmp/tmux.$(date +%Y%m%d%H%M%S).html; tmux capture-pane -p -e -S - -E - | aha --title "code" --style "zoom:110%" > "$FILENAME" && (if [[ $(uname) == "Darwin" ]]; then open "$FILENAME" 2>/dev/null || echo -n "$FILENAME" | pbcopy; else xdg-open "$FILENAME" 2>/dev/null || echo -n "$FILENAME" | xclip -in -selection clipboard; fi) && tmux display -d 1500 "█▓▒░ Captured! $FILENAME ░▒▓█"'

# default statusbar colors
set -g status-style bg=colour235,fg=colour136,default
# default window title colors
setw -g window-status-style fg=colour244,bg=default
#setw -g window-status-attr dim
# active window title colors
setw -g window-status-current-style fg=colour166,bg=default
#setw -g window-status-current-attr bright
# window title string (uses statusbar variables)
set -g set-titles-string '#T'
set -g status-justify "centre"
set -g window-status-format '#I #W'
set -g window-status-current-format ' #I #W '
# pane border
set -g pane-active-border-style fg='#55ff55'
set -g pane-border-style fg='#555555'

