# Enable flakes and prefer domestic binary caches
experimental-features = nix-command flakes
substituters = https://mirror.sjtu.edu.cn/nix-channels/store https://mirrors.ustc.edu.cn/nix-channels/store https://cache.nixos.org/
