check "installer advertises the Mise toolchain option" "./bootstrap.sh --help | grep -q -- '--toolchain     Install Node.js, Python, Go, and Rust with Mise (macOS only)'"
check "installer advertises Home Manager profiles" "./bootstrap.sh --help | grep -q -- '--profile NAME'"
check "installer advertises explicit Home Manager activation" "./bootstrap.sh --help | grep -q -- '--home-manager'"
check "installer parses the toolchain option" "bash -c 'source ./bootstrap.sh; ybw::plan::reset; ybw::plan::parse --toolchain; [[ \"\$YBW_INSTALL_PLAN_TOOLCHAIN\" == true ]]'"
check "installer parses the desktop Home Manager profile" "bash -c 'source ./bootstrap.sh; ybw::plan::reset; ybw::plan::parse --home-manager --profile desktop; [[ \"\$YBW_INSTALL_PLAN_HOME_MANAGER\" == true && \"\$YBW_INSTALL_PLAN_HOME_MANAGER_PROFILE\" == desktop ]]'"
check "installer parses explicit Home Manager activation" "bash -c 'source ./bootstrap.sh; ybw::plan::reset; ybw::plan::parse --home-manager; [[ \"\$YBW_INSTALL_PLAN_HOME_MANAGER\" == true ]]'"
check "Windows installer deploys from the home mirror" "grep -Fq 'home\\.config\\wezterm' bootstrap.ps1 && ! grep -Fq '\\.\\.config\\wezterm' bootstrap.ps1"
check "Nix installer has a non-mutating dry run" "test -x installer/install-nix.sh && ./installer/install-nix.sh --dry-run | grep -Fq 'Would install Nix'"
check "Nix installer prefers TUNA with official fallback" "grep -Fq 'https://mirrors.tuna.tsinghua.edu.cn/nix/latest/install' installer/install-nix.sh && grep -Fq 'https://nixos.org/nix/install' installer/install-nix.sh"
check "Nix installer configures Flakes without legacy channels" "grep -Fq -- '--no-channel-add' installer/install-nix.sh && grep -Fq -- '--nix-extra-conf-file \"\$NIX_CONFIG_SOURCE\"' installer/install-nix.sh"
check "Nix installer uses daemon mode for any systemd Linux" "mode_body=\$(sed -n '/^resolve_install_mode()/,/^}/p' installer/install-nix.sh); grep -Fq 'is_linux && has_systemd' <<< \"\$mode_body\" && ! grep -Fq '! is_wsl' <<< \"\$mode_body\""
check "Nix installer configures existing multi-user daemons" "grep -Fq 'NIX_DAEMON_CONFIG_FRAGMENT=\"/etc/nix/nix.conf.d/dotfiles.conf\"' installer/install-nix.sh && grep -Fq 'include \$NIX_DAEMON_CONFIG_FRAGMENT' installer/install-nix.sh && grep -Fq 'restart_nix_daemon' installer/install-nix.sh"
