[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#eff0eb"
yellow = "#f3f99d"

[colors.cursor]
cursor = "#97979b"

[colors.normal]
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.selection]
background = "#feffff"
text = "#282a36"

[cursor]
style = "Block"
unfocused_hollow = false

[env]
TERM = "xterm-256color"

[font]
size = 14.0


[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/local/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
startup_mode = "Windowed"

[window.dimensions]
columns = 180
lines = 140

[window.padding]
x = 0
y = 0
